# Generated by Django 5.2.10 on 2026-01-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='document',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='document',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='document',
            name='policy_number',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='zip_code',
        ),
    ]
